version: '3'
services:
  db-service:
    image: mysql:8.0.32-debian
    container_name: db-service
    hostname: db-service
    expose:
      - 3306
    volumes:
      #      - ./database:/var/lib/mysql
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=03092001
      - MYSQL_DATABASE=soc
    networks:
      - soc-network

  soc-registry:
    image: sudo248dev/soc-registry:0.0.1
    container_name: soc-registry
    hostname: soc-registry
    networks:
      - soc-network
    ports:
      - "8761:8761"

  api-gateway:
    image: sudo248dev/api-gateway:0.0.1
    container_name: api-gateway
    hostname: api-gateway
    depends_on:
      - soc-registry
    networks:
      - soc-network
    ports:
      - "9030:9030"

  image-service:
    image: sudo248dev/image-service:0.0.1
    container_name: image-service
    hostname: image-service
    depends_on:
      - soc-registry
    networks:
      - soc-network
    volumes:
      - ./image-service/uploads/images:/app/image-service/uploads/images

  auth-service:
    image: sudo248dev/auth-service:0.0.1
    container_name: auth-service
    hostname: auth-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  discovery-service:
    image: sudo248dev/discovery-service:0.0.1
    container_name: discovery-service
    hostname: discovery-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  payment-service:
    image: sudo248dev/payment-service:0.0.1
    container_name: payment-service
    hostname: payment-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  user-service:
    image: sudo248dev/user-service:0.0.1
    container_name: user-service
    hostname: user-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  cart-service:
    image: sudo248dev/cart-service:0.0.1
    container_name: cart-service
    hostname: cart-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  invoice-service:
    image: sudo248dev/invoice-service:0.0.1
    container_name: invoice-service
    hostname: invoice-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  promotion-service:
    image: sudo248dev/promotion-service:0.0.1
    container_name: promotion-service
    hostname: promotion-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  notification-service:
    image: sudo248dev/notification-service:0.0.1
    container_name: notification-service
    hostname: notification-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

  chat-service:
    image: sudo248dev/chat-service:0.0.1
    container_name: chat-service
    hostname: chat-service
    depends_on:
      - soc-registry
      - db-service
    networks:
      - soc-network

networks:
  soc-network:
    external: true